modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/IamShmilyou/LazyChunk/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://space.bilibili.com/1576498148?spm_id_from=333.1007.0.0"
logoFile="assets/lazy_chunks/icon.png"
authors="rizen, Shmily"
description='''
Reduces client stutters by spreading chunk loading across multiple frames.
'''

[[mixins]]
config="lazy_chunks.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="sodiumoptionsapi"
type="optional"
versionRange="*"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="fabric_api_base"
type="optional"
versionRange="*"
ordering="AFTER"
side="CLIENT"
